# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3489f1f743ebf7e456dd6b3a7891558f2e44f7ac81d02d8af3d0a0cf79128d0a253102e0fbe6ec5e82face23571bec25c525e3173dafdcbe694985489a2040bc

test:
  secret_key_base: 56232e6104b8d2749ca28fdc3dd6194edeb26ccaf7aaf88a74bd4c881222c95a7492390703ad11c60eee20564afadf7a814d46a0a8b348a5190e855e089ef852

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
