# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create( name: 'Star Wars' }, { name: 'Lord of the Rings' )
#   Character.create(name: 'Luke', movie: movies.first)
#admin

# Startup.create!(name:'Acordis International', address:'Miami, FL', latitude: '25.7611', longitude: '-80.1912', shortdescription: 'company short description', founded_date: '01/02/2000', website: 'http://www.wyncode.co', approval: true, email: 'aa@aa.com', description: 'long long long description long long long descriptionlong long long descriptionlong long long description', vertical: 1)
# Startup.create!(name:'Fresh Meal Plan', address:'Miami, FL', latitude: '25.8711', longitude: '-80.2912', shortdescription: 'company short description', founded_date: '01/02/2000', website: 'http://www.wyncode.co', approval: true, email: 'aa@aa.com', description: 'long long long description long long long descriptionlong long long descriptionlong long long description', vertical: 1)
# Startup.create!(name:'DG3 Media Group', address:'Orlando, FL', latitude: '26.5389', longitude: '-81.3798', shortdescription: 'company short description', founded_date: '01/02/2000', website: 'http://www.wyncode.co', approval: true, email: 'aa@aa.com', description: 'long long long description long long long descriptionlong long long descriptionlong long long description', vertical: 1)
# Startup.create!(name:'E-Telequote Insurance', address:'Tampa, FL', latitude: '27.9501', longitude: '-82.4578', shortdescription: 'company short description', founded_date: '01/02/2000', website: 'http://www.wyncode.co', approval: true, email: 'aa@aa.com', description: 'long long long description long long long descriptionlong long long descriptionlong long long description', vertical: 1)
# Startup.create!(name:'Resell MFG', address:'Orlando, FL', latitude: '26.7487', longitude: '-81.6398', shortdescription: 'company short description', founded_date: '01/02/2000', website: 'http://www.wyncode.co', approval: true, email: 'aa@aa.com', description: 'long long long description long long long descriptionlong long long descriptionlong long long description', vertical: 1)
#
# Investor.create!(name:'Citibank', address:'Miami, FL', latitude: '25.9451', longitude: '-80.1961', shortdescription: 'company short description', founded_date: '01/02/2000', website: 'http://www.wyncode.co', approval: true, email: 'aa@aa.com', description: 'long long long description long long long descriptionlong long long descriptionlong long long description', vertical: 1)
# Investor.create!(name:'Mario', address:'Miami, FL', latitude: '25.6551', longitude: '-80.1981', shortdescription: 'company short description', founded_date: '01/02/2000', website: 'http://www.wyncode.co', approval: true, email: 'aa@aa.com', description: 'long long long description long long long descriptionlong long long descriptionlong long long description', vertical: 1)
# Investor.create!(name:'HSBC', address:'Orlando, FL', latitude: '26.7539', longitude: '-81.5747', shortdescription: 'company short description', founded_date: '01/02/2000', website: 'http://www.wyncode.co', approval: true, email: 'aa@aa.com', description: 'long long long description long long long descriptionlong long long descriptionlong long long description', vertical: 1)
# Investor.create!(name:'Fundation', address:'Tampa, FL', latitude: '27.9354', longitude: '-82.4522', shortdescription: 'company short description', founded_date: '01/02/2000', website: 'http://www.wyncode.co', approval: true, email: 'aa@aa.com', description: 'long long long description long long long descriptionlong long long descriptionlong long long description', vertical: 1)
# Investor.create!(name:'University of Miami', address:'Orlando, FL', latitude: '26.5752', longitude: '-81.9325', shortdescription: 'company short description', founded_date: '01/02/2000', website: 'http://www.wyncode.co', approval: true, email: 'aa@aa.com', description: 'long long long description long long long descriptionlong long long descriptionlong long long description', vertical: 1)

#New Startups

# Startup.create!(name:"InnFocus Inc", website:"http://innfocusinc.com", address:"12415 SW 136th Ave #3, Miami, FL 33186", latitude:"25.65129", longitude:"-80.415978", description:"InnFocus is an ophthalmology company with extensive biomaterials experience, which develops and provides next-generation products for glaucoma surgery.", vertical: 2, employee_count:"16", stage:"C", founded_date:"11-05-2013", approval: true)
#
# Startup.create!(name:"Open English", website:"http://openenglish.com", address:"2901 Florida Ave #840, Miami, FL 33133", latitude:"25.72941", longitude:"-80.2429445", description:"Open English is a leading Education Technology company focused on English language learning for the Latin American & U.S. Hispanic markets.", vertical: 8, employee_count:"898", stage:"Late", founded_date:"04-04-2013", approval: true)
#
# Startup.create!(name:"Shooger", website:"http://shooger.com", address:"3211 Ponce De Leon Blvd #101, Coral Gables, FL 33134", latitude:"25.7488508", longitude:"-80.2672069", description:"Shooger is a mobile marketing platform that enables merchants to connect with smartphone-savvy consumers.", vertical: 18, employee_count:"32", stage:"A", founded_date:"04-04-2013", approval: true)
#
# Startup.create!(name:"Tissuetech", website:"http://biotissue.com", address:"7000 SW 97th Ave #211, Miami, FL 33173", latitude:"25.7512329", longitude:"-80.4114491", description:"issueTech, Inc., the parent company of both Amniox Medical, Inc. and BioTissue, Inc., is a leader in regenerative amniotic tissue-based products for use in the ophthalmology, optometry, musculoskeletal and wound care markets. The Company’s first product, AmnioGraft®, is the only tissue graft designated by the FDA as homologous for promoting ophthalmic wound healing while suppressing scarring and inflammation.", vertical: 2, employee_count:"43", stage:"B", founded_date:"07-16-2013", approval: true)
#
# Startup.create!(name:"Shooger", website:"http://shooger.com", address:"3211 Ponce De Leon Blvd #101, Coral Gables, FL 33134", latitude:"25.7488508", longitude:"-80.2672069", description:"Shooger is a mobile marketing platform that enables merchants to connect with smartphone-savvy consumers.", vertical: 18, employee_count:"32", stage:"A", founded_date:"04-04-2013", approval: true)
