# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create( name: 'Star Wars' }, { name: 'Lord of the Rings' )
#   Character.create(name: 'Luke', movie: movies.first)

Startup.create!(name:'Acordis International', address:'Miami, FL', latitude: '25.7617', longitude: '-80.1918', shortdescription: 'company short description', founded_date: '01/02/2000', website: 'http://www.wyncode.co', approval: true, email: 'aa@aa.com', description: 'long long long description long long long descriptionlong long long descriptionlong long long description', vertical: 1)
Startup.create!(name:'Fresh Meal Plan', address:'Miami, FL', latitude: '25.8717', longitude: '-78.1918', shortdescription: 'company short description', founded_date: '01/02/2000', website: 'http://www.wyncode.co', approval: true, email: 'aa@aa.com', description: 'long long long description long long long descriptionlong long long descriptionlong long long description', vertical: 1)
Startup.create!(name:'DG3 Media Group', address:'Orlando, FL', latitude: '28.5383', longitude: '-81.3792', shortdescription: 'company short description', founded_date: '01/02/2000', website: 'http://www.wyncode.co', approval: true, email: 'aa@aa.com', description: 'long long long description long long long descriptionlong long long descriptionlong long long description', vertical: 1)
Startup.create!(name:'E-Telequote Insurance', address:'Tampa, FL', latitude: '27.9506', longitude: '-82.4572', shortdescription: 'company short description', founded_date: '01/02/2000', website: 'http://www.wyncode.co', approval: true, email: 'aa@aa.com', description: 'long long long description long long long descriptionlong long long descriptionlong long long description', vertical: 1)
Startup.create!(name:'Resell MFG', address:'Orlando, FL', latitude: '28.7483', longitude: '-81.6392', shortdescription: 'company short description', founded_date: '01/02/2000', website: 'http://www.wyncode.co', approval: true, email: 'aa@aa.com', description: 'long long long description long long long descriptionlong long long descriptionlong long long description', vertical: 1)

Investor.create!(name:'Citibank', address:'Miami, FL', latitude: '25.7657', longitude: '-80.1968', shortdescription: 'company short description', founded_date: '01/02/2000', website: 'http://www.wyncode.co', approval: true, email: 'aa@aa.com', description: 'long long long description long long long descriptionlong long long descriptionlong long long description', vertical: 1)
Investor.create!(name:'Mario', address:'Miami, FL', latitude: '25.8757', longitude: '-78.1968', shortdescription: 'company short description', founded_date: '01/02/2000', website: 'http://www.wyncode.co', approval: true, email: 'aa@aa.com', description: 'long long long description long long long descriptionlong long long descriptionlong long long description', vertical: 1)
Investor.create!(name:'HSBC', address:'Orlando, FL', latitude: '28.5333', longitude: '-81.3742', shortdescription: 'company short description', founded_date: '01/02/2000', website: 'http://www.wyncode.co', approval: true, email: 'aa@aa.com', description: 'long long long description long long long descriptionlong long long descriptionlong long long description', vertical: 1)
Investor.create!(name:'Knight Fundation', address:'Tampa, FL', latitude: '27.9556', longitude: '-82.4522', shortdescription: 'company short description', founded_date: '01/02/2000', website: 'http://www.wyncode.co', approval: true, email: 'aa@aa.com', description: 'long long long description long long long descriptionlong long long descriptionlong long long description', vertical: 1)
Investor.create!(name:'University of Miami', address:'Orlando, FL', latitude: '28.7453', longitude: '-81.6322', shortdescription: 'company short description', founded_date: '01/02/2000', website: 'http://www.wyncode.co', approval: true, email: 'aa@aa.com', description: 'long long long description long long long descriptionlong long long descriptionlong long long description', vertical: 1)
